// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmdId.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.contract.protobuf;

public final class MsgCmd {
  private MsgCmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code helloim.protocol.CmdId}
   */
  public enum CmdId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CMD_ID_DEFAULT = 0;</code>
     */
    CMD_ID_DEFAULT(0),
    /**
     * <pre>
     * echo
     * </pre>
     *
     * <code>CMD_ID_ECHO = 1;</code>
     */
    CMD_ID_ECHO(1),
    /**
     * <pre>
     * 单聊上行
     * </pre>
     *
     * <code>CMD_ID_C2CSEND = 1006;</code>
     */
    CMD_ID_C2CSEND(1006),
    /**
     * <pre>
     * 单聊下行
     * </pre>
     *
     * <code>CMD_ID_C2CPUSH = 1007;</code>
     */
    CMD_ID_C2CPUSH(1007),
    /**
     * <pre>
     * 群聊上行
     * </pre>
     *
     * <code>CMD_ID_C2CPUSTH = 1008;</code>
     */
    CMD_ID_C2CPUSTH(1008),
    /**
     * <pre>
     * 群聊下行
     * </pre>
     *
     * <code>CMD_ID_C2GPUSH = 1009;</code>
     */
    CMD_ID_C2GPUSH(1009),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CMD_ID_DEFAULT = 0;</code>
     */
    public static final int CMD_ID_DEFAULT_VALUE = 0;
    /**
     * <pre>
     * echo
     * </pre>
     *
     * <code>CMD_ID_ECHO = 1;</code>
     */
    public static final int CMD_ID_ECHO_VALUE = 1;
    /**
     * <pre>
     * 单聊上行
     * </pre>
     *
     * <code>CMD_ID_C2CSEND = 1006;</code>
     */
    public static final int CMD_ID_C2CSEND_VALUE = 1006;
    /**
     * <pre>
     * 单聊下行
     * </pre>
     *
     * <code>CMD_ID_C2CPUSH = 1007;</code>
     */
    public static final int CMD_ID_C2CPUSH_VALUE = 1007;
    /**
     * <pre>
     * 群聊上行
     * </pre>
     *
     * <code>CMD_ID_C2CPUSTH = 1008;</code>
     */
    public static final int CMD_ID_C2CPUSTH_VALUE = 1008;
    /**
     * <pre>
     * 群聊下行
     * </pre>
     *
     * <code>CMD_ID_C2GPUSH = 1009;</code>
     */
    public static final int CMD_ID_C2GPUSH_VALUE = 1009;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CmdId valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CmdId forNumber(int value) {
      switch (value) {
        case 0: return CMD_ID_DEFAULT;
        case 1: return CMD_ID_ECHO;
        case 1006: return CMD_ID_C2CSEND;
        case 1007: return CMD_ID_C2CPUSH;
        case 1008: return CMD_ID_C2CPUSTH;
        case 1009: return CMD_ID_C2GPUSH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CmdId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdId>() {
            public CmdId findValueByNumber(int number) {
              return CmdId.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.xuning888.helloim.contract.protobuf.MsgCmd.getDescriptor().getEnumTypes().get(0);
    }

    private static final CmdId[] VALUES = values();

    public static CmdId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CmdId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:helloim.protocol.CmdId)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013cmdId.proto\022\020helloim.protocol*\201\001\n\005CmdI" +
      "d\022\022\n\016CMD_ID_DEFAULT\020\000\022\017\n\013CMD_ID_ECHO\020\001\022\023" +
      "\n\016CMD_ID_C2CSEND\020\356\007\022\023\n\016CMD_ID_C2CPUSH\020\357\007" +
      "\022\024\n\017CMD_ID_C2CPUSTH\020\360\007\022\023\n\016CMD_ID_C2GPUSH" +
      "\020\361\007B8\n.com.github.xuning888.helloim.cont" +
      "ract.protobufB\006MsgCmdb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
