server:
  port: 8087
  tomcat:
    max-connections: 10000
    accept-count: 10000
    connection-timeout: 30000
    threads:
      max: 300
spring:
  profiles:
    active: dev
  application:
    name: helloim-webapi
dubbo:
  application:
    name: helloim-webapi
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
  registry:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
    group: helloim
    timeout: 10000
  consumer:
    check: false
  protocol:
    name: tri
    threadpool: fixed
    threads: 200