server:
  port: 8083
spring:
  profiles:
    active: dev
  application:
    name: helloim-session
  redis:
    host: ${REDIS_ADDR}
dubbo:
  application:
    name: helloim-session
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS}
  registry:
    address: ${ZK_ADDRESS}
    group: helloim
    timeout: 10000
  consumer:
    check: false
  protocol:
    name: tri
    threadpool: fixed
    threads: 200