// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/chat/v1/chat_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.chat.v1;

public final class ChatServiceProto {
  private ChatServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerSeqRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerSeqRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerSeqResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerSeqResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrActivateChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateOrActivateChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrActivateChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateOrActivateChatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetChatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036api/chat/v1/chat_service.proto\032\033api/co" +
      "mmon/v1/message.proto\032\030api/common/v1/cha" +
      "t.proto\032$api/store/v1/msg_store_service." +
      "proto\032%api/store/v1/chat_store_service.p" +
      "roto\"O\n\020ServerSeqRequest\022\014\n\004from\030\001 \001(\t\022\n" +
      "\n\002to\030\002 \001(\t\022\020\n\010chatType\030\003 \001(\005\022\017\n\007traceId\030" +
      "\004 \001(\t\"&\n\021ServerSeqResponse\022\021\n\tserverSeq\030" +
      "\001 \001(\003\"`\n\033CreateOrActivateChatRequest\022\016\n\006" +
      "userId\030\001 \001(\003\022\016\n\006chatId\030\002 \001(\003\022\020\n\010chatType" +
      "\030\003 \001(\005\022\017\n\007traceId\030\004 \001(\t\"7\n\034CreateOrActiv" +
      "ateChatResponse\022\027\n\006imChat\030\001 \001(\0132\007.ImChat" +
      "\"A\n\016GetChatRequest\022\016\n\006userId\030\001 \001(\003\022\016\n\006ch" +
      "atId\030\002 \001(\003\022\017\n\007traceId\030\003 \001(\t\"*\n\017GetChatRe" +
      "sponse\022\027\n\006imChat\030\001 \001(\0132\007.ImChat2\265\002\n\013Chat" +
      "Service\0222\n\tserverSeq\022\021.ServerSeqRequest\032" +
      "\022.ServerSeqResponse\022S\n\024createOrActivateC" +
      "hat\022\034.CreateOrActivateChatRequest\032\035.Crea" +
      "teOrActivateChatResponse\0225\n\ngetAllChat\022\022" +
      ".GetAllChatRequest\032\023.GetAllChatResponse\022" +
      "8\n\013lastMessage\022\023.LastMessageRequest\032\024.La" +
      "stMessageResponse\022,\n\007getChat\022\017.GetChatRe" +
      "quest\032\020.GetChatResponseBG\n1com.github.xu" +
      "ning888.helloim.api.protobuf.chat.v1B\020Ch" +
      "atServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.getDescriptor(),
          com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.getDescriptor(),
          com.github.xuning888.helloim.api.protobuf.store.v1.MsgStoreServiceProto.getDescriptor(),
          com.github.xuning888.helloim.api.protobuf.store.v1.ChatStoreServiceProto.getDescriptor(),
        });
    internal_static_ServerSeqRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerSeqRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerSeqRequest_descriptor,
        new java.lang.String[] { "From", "To", "ChatType", "TraceId", });
    internal_static_ServerSeqResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServerSeqResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerSeqResponse_descriptor,
        new java.lang.String[] { "ServerSeq", });
    internal_static_CreateOrActivateChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreateOrActivateChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateOrActivateChatRequest_descriptor,
        new java.lang.String[] { "UserId", "ChatId", "ChatType", "TraceId", });
    internal_static_CreateOrActivateChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CreateOrActivateChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateOrActivateChatResponse_descriptor,
        new java.lang.String[] { "ImChat", });
    internal_static_GetChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChatRequest_descriptor,
        new java.lang.String[] { "UserId", "ChatId", "TraceId", });
    internal_static_GetChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetChatResponse_descriptor,
        new java.lang.String[] { "ImChat", });
    com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.getDescriptor();
    com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.getDescriptor();
    com.github.xuning888.helloim.api.protobuf.store.v1.MsgStoreServiceProto.getDescriptor();
    com.github.xuning888.helloim.api.protobuf.store.v1.ChatStoreServiceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
