// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/chat/v1/chat_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.chat.v1;

public interface CreateOrActivateChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateOrActivateChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 chatId = 2;</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <code>int32 chatType = 3;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <code>string traceId = 4;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 4;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
