// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/chat/v1/chat_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.chat.v1;

public interface CreateOrActivateChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateOrActivateChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImChat imChat = 1;</code>
   * @return Whether the imChat field is set.
   */
  boolean hasImChat();
  /**
   * <code>.ImChat imChat = 1;</code>
   * @return The imChat.
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ImChat getImChat();
  /**
   * <code>.ImChat imChat = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder getImChatOrBuilder();
}
