// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/chat/v1/chat_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.chat.v1;

public interface ServerSeqResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerSeqResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 serverSeq = 1;</code>
   * @return The serverSeq.
   */
  long getServerSeq();
}
