// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/chat_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

/**
 * Protobuf type {@code BatchCreateOrUpdateRequest}
 */
public final class BatchCreateOrUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BatchCreateOrUpdateRequest)
    BatchCreateOrUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatchCreateOrUpdateRequest.newBuilder() to construct.
  private BatchCreateOrUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchCreateOrUpdateRequest() {
    chats_ = java.util.Collections.emptyList();
    traceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BatchCreateOrUpdateRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.xuning888.helloim.api.protobuf.store.v1.ChatStoreServiceProto.internal_static_BatchCreateOrUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.xuning888.helloim.api.protobuf.store.v1.ChatStoreServiceProto.internal_static_BatchCreateOrUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest.class, com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest.Builder.class);
  }

  public static final int CHATS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ImChat> chats_;
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ImChat> getChatsList() {
    return chats_;
  }
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder> 
      getChatsOrBuilderList() {
    return chats_;
  }
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  @java.lang.Override
  public int getChatsCount() {
    return chats_.size();
  }
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat getChats(int index) {
    return chats_.get(index);
  }
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder getChatsOrBuilder(
      int index) {
    return chats_.get(index);
  }

  public static final int TRACEID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <code>string traceId = 2;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <code>string traceId = 2;</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < chats_.size(); i++) {
      output.writeMessage(1, chats_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, traceId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < chats_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chats_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, traceId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest)) {
      return super.equals(obj);
    }
    com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest other = (com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest) obj;

    if (!getChatsList()
        .equals(other.getChatsList())) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChatsCount() > 0) {
      hash = (37 * hash) + CHATS_FIELD_NUMBER;
      hash = (53 * hash) + getChatsList().hashCode();
    }
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BatchCreateOrUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BatchCreateOrUpdateRequest)
      com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.ChatStoreServiceProto.internal_static_BatchCreateOrUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.ChatStoreServiceProto.internal_static_BatchCreateOrUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest.class, com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest.Builder.class);
    }

    // Construct using com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (chatsBuilder_ == null) {
        chats_ = java.util.Collections.emptyList();
      } else {
        chats_ = null;
        chatsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      traceId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.ChatStoreServiceProto.internal_static_BatchCreateOrUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest getDefaultInstanceForType() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest build() {
      com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest buildPartial() {
      com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest result = new com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest result) {
      if (chatsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          chats_ = java.util.Collections.unmodifiableList(chats_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chats_ = chats_;
      } else {
        result.chats_ = chatsBuilder_.build();
      }
    }

    private void buildPartial0(com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.traceId_ = traceId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest) {
        return mergeFrom((com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest other) {
      if (other == com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest.getDefaultInstance()) return this;
      if (chatsBuilder_ == null) {
        if (!other.chats_.isEmpty()) {
          if (chats_.isEmpty()) {
            chats_ = other.chats_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChatsIsMutable();
            chats_.addAll(other.chats_);
          }
          onChanged();
        }
      } else {
        if (!other.chats_.isEmpty()) {
          if (chatsBuilder_.isEmpty()) {
            chatsBuilder_.dispose();
            chatsBuilder_ = null;
            chats_ = other.chats_;
            bitField0_ = (bitField0_ & ~0x00000001);
            chatsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChatsFieldBuilder() : null;
          } else {
            chatsBuilder_.addAllMessages(other.chats_);
          }
        }
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.github.xuning888.helloim.api.protobuf.common.v1.ImChat m =
                  input.readMessage(
                      com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.parser(),
                      extensionRegistry);
              if (chatsBuilder_ == null) {
                ensureChatsIsMutable();
                chats_.add(m);
              } else {
                chatsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ImChat> chats_ =
      java.util.Collections.emptyList();
    private void ensureChatsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        chats_ = new java.util.ArrayList<com.github.xuning888.helloim.api.protobuf.common.v1.ImChat>(chats_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.xuning888.helloim.api.protobuf.common.v1.ImChat, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder, com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder> chatsBuilder_;

    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ImChat> getChatsList() {
      if (chatsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(chats_);
      } else {
        return chatsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public int getChatsCount() {
      if (chatsBuilder_ == null) {
        return chats_.size();
      } else {
        return chatsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat getChats(int index) {
      if (chatsBuilder_ == null) {
        return chats_.get(index);
      } else {
        return chatsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder setChats(
        int index, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat value) {
      if (chatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatsIsMutable();
        chats_.set(index, value);
        onChanged();
      } else {
        chatsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder setChats(
        int index, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder builderForValue) {
      if (chatsBuilder_ == null) {
        ensureChatsIsMutable();
        chats_.set(index, builderForValue.build());
        onChanged();
      } else {
        chatsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder addChats(com.github.xuning888.helloim.api.protobuf.common.v1.ImChat value) {
      if (chatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatsIsMutable();
        chats_.add(value);
        onChanged();
      } else {
        chatsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder addChats(
        int index, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat value) {
      if (chatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatsIsMutable();
        chats_.add(index, value);
        onChanged();
      } else {
        chatsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder addChats(
        com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder builderForValue) {
      if (chatsBuilder_ == null) {
        ensureChatsIsMutable();
        chats_.add(builderForValue.build());
        onChanged();
      } else {
        chatsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder addChats(
        int index, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder builderForValue) {
      if (chatsBuilder_ == null) {
        ensureChatsIsMutable();
        chats_.add(index, builderForValue.build());
        onChanged();
      } else {
        chatsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder addAllChats(
        java.lang.Iterable<? extends com.github.xuning888.helloim.api.protobuf.common.v1.ImChat> values) {
      if (chatsBuilder_ == null) {
        ensureChatsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chats_);
        onChanged();
      } else {
        chatsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder clearChats() {
      if (chatsBuilder_ == null) {
        chats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        chatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public Builder removeChats(int index) {
      if (chatsBuilder_ == null) {
        ensureChatsIsMutable();
        chats_.remove(index);
        onChanged();
      } else {
        chatsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder getChatsBuilder(
        int index) {
      return getChatsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder getChatsOrBuilder(
        int index) {
      if (chatsBuilder_ == null) {
        return chats_.get(index);  } else {
        return chatsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public java.util.List<? extends com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder> 
         getChatsOrBuilderList() {
      if (chatsBuilder_ != null) {
        return chatsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(chats_);
      }
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder addChatsBuilder() {
      return getChatsFieldBuilder().addBuilder(
          com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.getDefaultInstance());
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder addChatsBuilder(
        int index) {
      return getChatsFieldBuilder().addBuilder(
          index, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.getDefaultInstance());
    }
    /**
     * <code>repeated .ImChat chats = 1;</code>
     */
    public java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder> 
         getChatsBuilderList() {
      return getChatsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.xuning888.helloim.api.protobuf.common.v1.ImChat, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder, com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder> 
        getChatsFieldBuilder() {
      if (chatsBuilder_ == null) {
        chatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.xuning888.helloim.api.protobuf.common.v1.ImChat, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder, com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder>(
                chats_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        chats_ = null;
      }
      return chatsBuilder_;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <code>string traceId = 2;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string traceId = 2;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string traceId = 2;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string traceId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string traceId = 2;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BatchCreateOrUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:BatchCreateOrUpdateRequest)
  private static final com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest();
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchCreateOrUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchCreateOrUpdateRequest>() {
    @java.lang.Override
    public BatchCreateOrUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchCreateOrUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchCreateOrUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.store.v1.BatchCreateOrUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

