// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/chat_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

public final class ChatStoreServiceProto {
  private ChatStoreServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrUpdateChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateOrUpdateChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrUpdateChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateOrUpdateChatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllChatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BatchCreateOrUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BatchCreateOrUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BatchCreateOrUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BatchCreateOrUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%api/store/v1/chat_store_service.proto\032" +
      "\033api/common/v1/message.proto\032\030api/common" +
      "/v1/chat.proto\"E\n\031CreateOrUpdateChatRequ" +
      "est\022\027\n\006imChat\030\001 \001(\0132\007.ImChat\022\017\n\007traceId\030" +
      "\002 \001(\t\"=\n\032CreateOrUpdateChatResponse\022\016\n\006r" +
      "esult\030\001 \001(\005\022\017\n\007traceId\030\002 \001(\t\"4\n\021GetAllCh" +
      "atRequest\022\016\n\006userId\030\001 \001(\t\022\017\n\007traceId\030\002 \001" +
      "(\t\",\n\022GetAllChatResponse\022\026\n\005chats\030\001 \003(\0132" +
      "\007.ImChat\"E\n\032BatchCreateOrUpdateRequest\022\026" +
      "\n\005chats\030\001 \003(\0132\007.ImChat\022\017\n\007traceId\030\002 \001(\t\"" +
      "-\n\033BatchCreateOrUpdateResponse\022\016\n\006result" +
      "\030\001 \001(\0052\346\001\n\020ChatStoreService\022I\n\016createOrU" +
      "pdate\022\032.CreateOrUpdateChatRequest\032\033.Crea" +
      "teOrUpdateChatResponse\0225\n\ngetAllChat\022\022.G" +
      "etAllChatRequest\032\023.GetAllChatResponse\022P\n" +
      "\023batchCreateOrUpdate\022\033.BatchCreateOrUpda" +
      "teRequest\032\034.BatchCreateOrUpdateResponseB" +
      "M\n2com.github.xuning888.helloim.api.prot" +
      "obuf.store.v1B\025ChatStoreServiceProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.getDescriptor(),
          com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.getDescriptor(),
        });
    internal_static_CreateOrUpdateChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateOrUpdateChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateOrUpdateChatRequest_descriptor,
        new java.lang.String[] { "ImChat", "TraceId", });
    internal_static_CreateOrUpdateChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateOrUpdateChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateOrUpdateChatResponse_descriptor,
        new java.lang.String[] { "Result", "TraceId", });
    internal_static_GetAllChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChatRequest_descriptor,
        new java.lang.String[] { "UserId", "TraceId", });
    internal_static_GetAllChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAllChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllChatResponse_descriptor,
        new java.lang.String[] { "Chats", });
    internal_static_BatchCreateOrUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BatchCreateOrUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BatchCreateOrUpdateRequest_descriptor,
        new java.lang.String[] { "Chats", "TraceId", });
    internal_static_BatchCreateOrUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_BatchCreateOrUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BatchCreateOrUpdateResponse_descriptor,
        new java.lang.String[] { "Result", });
    com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.getDescriptor();
    com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
