// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/chat_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

public interface CreateOrUpdateChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateOrUpdateChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();

  /**
   * <code>string traceId = 2;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 2;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
