// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/chat_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

public interface GetAllChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ImChat> 
      getChatsList();
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ImChat getChats(int index);
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  int getChatsCount();
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  java.util.List<? extends com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder> 
      getChatsOrBuilderList();
  /**
   * <code>repeated .ImChat chats = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder getChatsOrBuilder(
      int index);
}
