// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/msg_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

public interface LastMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LastMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ChatMessage lastMessage = 1;</code>
   * @return Whether the lastMessage field is set.
   */
  boolean hasLastMessage();
  /**
   * <code>.ChatMessage lastMessage = 1;</code>
   * @return The lastMessage.
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getLastMessage();
  /**
   * <code>.ChatMessage lastMessage = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder getLastMessageOrBuilder();
}
