// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/msg_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

/**
 * Protobuf type {@code SaveMessageRequest}
 */
public final class SaveMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SaveMessageRequest)
    SaveMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SaveMessageRequest.newBuilder() to construct.
  private SaveMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SaveMessageRequest() {
    traceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SaveMessageRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.xuning888.helloim.api.protobuf.store.v1.MsgStoreServiceProto.internal_static_SaveMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.xuning888.helloim.api.protobuf.store.v1.MsgStoreServiceProto.internal_static_SaveMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest.class, com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CHATMESSAGE_FIELD_NUMBER = 1;
  private com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage chatMessage_;
  /**
   * <code>.ChatMessage chatMessage = 1;</code>
   * @return Whether the chatMessage field is set.
   */
  @java.lang.Override
  public boolean hasChatMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ChatMessage chatMessage = 1;</code>
   * @return The chatMessage.
   */
  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getChatMessage() {
    return chatMessage_ == null ? com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.getDefaultInstance() : chatMessage_;
  }
  /**
   * <code>.ChatMessage chatMessage = 1;</code>
   */
  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder getChatMessageOrBuilder() {
    return chatMessage_ == null ? com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.getDefaultInstance() : chatMessage_;
  }

  public static final int TRACEID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <code>string traceId = 2;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <code>string traceId = 2;</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getChatMessage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, traceId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChatMessage());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, traceId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest)) {
      return super.equals(obj);
    }
    com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest other = (com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest) obj;

    if (hasChatMessage() != other.hasChatMessage()) return false;
    if (hasChatMessage()) {
      if (!getChatMessage()
          .equals(other.getChatMessage())) return false;
    }
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChatMessage()) {
      hash = (37 * hash) + CHATMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getChatMessage().hashCode();
    }
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SaveMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SaveMessageRequest)
      com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.MsgStoreServiceProto.internal_static_SaveMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.MsgStoreServiceProto.internal_static_SaveMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest.class, com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest.Builder.class);
    }

    // Construct using com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChatMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      chatMessage_ = null;
      if (chatMessageBuilder_ != null) {
        chatMessageBuilder_.dispose();
        chatMessageBuilder_ = null;
      }
      traceId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.MsgStoreServiceProto.internal_static_SaveMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest getDefaultInstanceForType() {
      return com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest build() {
      com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest buildPartial() {
      com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest result = new com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.chatMessage_ = chatMessageBuilder_ == null
            ? chatMessage_
            : chatMessageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.traceId_ = traceId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest) {
        return mergeFrom((com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest other) {
      if (other == com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest.getDefaultInstance()) return this;
      if (other.hasChatMessage()) {
        mergeChatMessage(other.getChatMessage());
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getChatMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage chatMessage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.Builder, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder> chatMessageBuilder_;
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     * @return Whether the chatMessage field is set.
     */
    public boolean hasChatMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     * @return The chatMessage.
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getChatMessage() {
      if (chatMessageBuilder_ == null) {
        return chatMessage_ == null ? com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.getDefaultInstance() : chatMessage_;
      } else {
        return chatMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     */
    public Builder setChatMessage(com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage value) {
      if (chatMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chatMessage_ = value;
      } else {
        chatMessageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     */
    public Builder setChatMessage(
        com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.Builder builderForValue) {
      if (chatMessageBuilder_ == null) {
        chatMessage_ = builderForValue.build();
      } else {
        chatMessageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     */
    public Builder mergeChatMessage(com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage value) {
      if (chatMessageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          chatMessage_ != null &&
          chatMessage_ != com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.getDefaultInstance()) {
          getChatMessageBuilder().mergeFrom(value);
        } else {
          chatMessage_ = value;
        }
      } else {
        chatMessageBuilder_.mergeFrom(value);
      }
      if (chatMessage_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     */
    public Builder clearChatMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      chatMessage_ = null;
      if (chatMessageBuilder_ != null) {
        chatMessageBuilder_.dispose();
        chatMessageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.Builder getChatMessageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getChatMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     */
    public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder getChatMessageOrBuilder() {
      if (chatMessageBuilder_ != null) {
        return chatMessageBuilder_.getMessageOrBuilder();
      } else {
        return chatMessage_ == null ?
            com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.getDefaultInstance() : chatMessage_;
      }
    }
    /**
     * <code>.ChatMessage chatMessage = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.Builder, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder> 
        getChatMessageFieldBuilder() {
      if (chatMessageBuilder_ == null) {
        chatMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.Builder, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder>(
                getChatMessage(),
                getParentForChildren(),
                isClean());
        chatMessage_ = null;
      }
      return chatMessageBuilder_;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <code>string traceId = 2;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string traceId = 2;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string traceId = 2;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string traceId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string traceId = 2;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SaveMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:SaveMessageRequest)
  private static final com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest();
  }

  public static com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SaveMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<SaveMessageRequest>() {
    @java.lang.Override
    public SaveMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SaveMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SaveMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.store.v1.SaveMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

