// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/msg_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

public interface SaveMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ChatMessage chatMessage = 1;</code>
   * @return Whether the chatMessage field is set.
   */
  boolean hasChatMessage();
  /**
   * <code>.ChatMessage chatMessage = 1;</code>
   * @return The chatMessage.
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getChatMessage();
  /**
   * <code>.ChatMessage chatMessage = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder getChatMessageOrBuilder();

  /**
   * <code>string traceId = 2;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 2;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
