// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/store/v1/msg_store_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.store.v1;

public interface SelectMessageByServerSeqsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SelectMessageByServerSeqsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ChatMessage messages = 1;</code>
   */
  java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage> 
      getMessagesList();
  /**
   * <code>repeated .ChatMessage messages = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getMessages(int index);
  /**
   * <code>repeated .ChatMessage messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .ChatMessage messages = 1;</code>
   */
  java.util.List<? extends com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .ChatMessage messages = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder getMessagesOrBuilder(
      int index);
}
