// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/message/v1/message_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.message.v1;

public final class MessageServiceProto {
  private MessageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullOfflineMsgRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PullOfflineMsgRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfflineMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfflineMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CleanOfflineMsgRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CleanOfflineMsgRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CleanOfflineMsgResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CleanOfflineMsgResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$api/message/v1/message_service.proto\032\033" +
      "api/common/v1/message.proto\"\230\001\n\025PullOffl" +
      "ineMsgRequest\022\022\n\nfromUserId\030\001 \001(\003\022\016\n\006cha" +
      "tId\030\002 \001(\003\022\020\n\010chatType\030\003 \001(\005\022\024\n\014minServer" +
      "Seq\030\004 \001(\003\022\024\n\014maxServerSeq\030\005 \001(\003\022\014\n\004size\030" +
      "\006 \001(\005\022\017\n\007traceId\030\007 \001(\t\"?\n\026OfflineMessage" +
      "Response\022%\n\017offlineMessages\030\001 \003(\0132\014.Chat" +
      "Message\"@\n\026CleanOfflineMsgRequest\022\025\n\roff" +
      "lineMsgKey\030\001 \001(\t\022\017\n\007traceId\030\002 \001(\t\"*\n\027Cle" +
      "anOfflineMsgResponse\022\017\n\007traceId\030\001 \001(\t2\352\001" +
      "\n\016MessageService\022A\n\016PullOfflineMsg\022\026.Pul" +
      "lOfflineMsgRequest\032\027.OfflineMessageRespo" +
      "nse\022K\n\030GetLatestOfflineMessages\022\026.PullOf" +
      "flineMsgRequest\032\027.OfflineMessageResponse" +
      "\022H\n\023CleanOfflineMessage\022\027.CleanOfflineMs" +
      "gRequest\032\030.CleanOfflineMsgResponseBM\n4co" +
      "m.github.xuning888.helloim.api.protobuf." +
      "message.v1B\023MessageServiceProtoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.getDescriptor(),
        });
    internal_static_PullOfflineMsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PullOfflineMsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PullOfflineMsgRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ChatId", "ChatType", "MinServerSeq", "MaxServerSeq", "Size", "TraceId", });
    internal_static_OfflineMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OfflineMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfflineMessageResponse_descriptor,
        new java.lang.String[] { "OfflineMessages", });
    internal_static_CleanOfflineMsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CleanOfflineMsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CleanOfflineMsgRequest_descriptor,
        new java.lang.String[] { "OfflineMsgKey", "TraceId", });
    internal_static_CleanOfflineMsgResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CleanOfflineMsgResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CleanOfflineMsgResponse_descriptor,
        new java.lang.String[] { "TraceId", });
    com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
