// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/message/v1/message_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.message.v1;

public interface PullOfflineMsgRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PullOfflineMsgRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fromUserId = 1;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <code>int64 chatId = 2;</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <code>int32 chatType = 3;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <code>int64 minServerSeq = 4;</code>
   * @return The minServerSeq.
   */
  long getMinServerSeq();

  /**
   * <code>int64 maxServerSeq = 5;</code>
   * @return The maxServerSeq.
   */
  long getMaxServerSeq();

  /**
   * <code>int32 size = 6;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>string traceId = 7;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 7;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
