// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/message/v1/message_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.message.v1;

/**
 * Protobuf type {@code PullOfflineMsgRequest}
 */
public final class PullOfflineMsgRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PullOfflineMsgRequest)
    PullOfflineMsgRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PullOfflineMsgRequest.newBuilder() to construct.
  private PullOfflineMsgRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PullOfflineMsgRequest() {
    traceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PullOfflineMsgRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.xuning888.helloim.api.protobuf.message.v1.MessageServiceProto.internal_static_PullOfflineMsgRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.xuning888.helloim.api.protobuf.message.v1.MessageServiceProto.internal_static_PullOfflineMsgRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest.class, com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest.Builder.class);
  }

  public static final int FROMUSERID_FIELD_NUMBER = 1;
  private long fromUserId_ = 0L;
  /**
   * <code>int64 fromUserId = 1;</code>
   * @return The fromUserId.
   */
  @java.lang.Override
  public long getFromUserId() {
    return fromUserId_;
  }

  public static final int CHATID_FIELD_NUMBER = 2;
  private long chatId_ = 0L;
  /**
   * <code>int64 chatId = 2;</code>
   * @return The chatId.
   */
  @java.lang.Override
  public long getChatId() {
    return chatId_;
  }

  public static final int CHATTYPE_FIELD_NUMBER = 3;
  private int chatType_ = 0;
  /**
   * <code>int32 chatType = 3;</code>
   * @return The chatType.
   */
  @java.lang.Override
  public int getChatType() {
    return chatType_;
  }

  public static final int MINSERVERSEQ_FIELD_NUMBER = 4;
  private long minServerSeq_ = 0L;
  /**
   * <code>int64 minServerSeq = 4;</code>
   * @return The minServerSeq.
   */
  @java.lang.Override
  public long getMinServerSeq() {
    return minServerSeq_;
  }

  public static final int MAXSERVERSEQ_FIELD_NUMBER = 5;
  private long maxServerSeq_ = 0L;
  /**
   * <code>int64 maxServerSeq = 5;</code>
   * @return The maxServerSeq.
   */
  @java.lang.Override
  public long getMaxServerSeq() {
    return maxServerSeq_;
  }

  public static final int SIZE_FIELD_NUMBER = 6;
  private int size_ = 0;
  /**
   * <code>int32 size = 6;</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int TRACEID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object traceId_ = "";
  /**
   * <code>string traceId = 7;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public java.lang.String getTraceId() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      traceId_ = s;
      return s;
    }
  }
  /**
   * <code>string traceId = 7;</code>
   * @return The bytes for traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTraceIdBytes() {
    java.lang.Object ref = traceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      traceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fromUserId_ != 0L) {
      output.writeInt64(1, fromUserId_);
    }
    if (chatId_ != 0L) {
      output.writeInt64(2, chatId_);
    }
    if (chatType_ != 0) {
      output.writeInt32(3, chatType_);
    }
    if (minServerSeq_ != 0L) {
      output.writeInt64(4, minServerSeq_);
    }
    if (maxServerSeq_ != 0L) {
      output.writeInt64(5, maxServerSeq_);
    }
    if (size_ != 0) {
      output.writeInt32(6, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, traceId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fromUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, fromUserId_);
    }
    if (chatId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, chatId_);
    }
    if (chatType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, chatType_);
    }
    if (minServerSeq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, minServerSeq_);
    }
    if (maxServerSeq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, maxServerSeq_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(traceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, traceId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest)) {
      return super.equals(obj);
    }
    com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest other = (com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest) obj;

    if (getFromUserId()
        != other.getFromUserId()) return false;
    if (getChatId()
        != other.getChatId()) return false;
    if (getChatType()
        != other.getChatType()) return false;
    if (getMinServerSeq()
        != other.getMinServerSeq()) return false;
    if (getMaxServerSeq()
        != other.getMaxServerSeq()) return false;
    if (getSize()
        != other.getSize()) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFromUserId());
    hash = (37 * hash) + CHATID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChatId());
    hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChatType();
    hash = (37 * hash) + MINSERVERSEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMinServerSeq());
    hash = (37 * hash) + MAXSERVERSEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxServerSeq());
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PullOfflineMsgRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PullOfflineMsgRequest)
      com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xuning888.helloim.api.protobuf.message.v1.MessageServiceProto.internal_static_PullOfflineMsgRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xuning888.helloim.api.protobuf.message.v1.MessageServiceProto.internal_static_PullOfflineMsgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest.class, com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest.Builder.class);
    }

    // Construct using com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fromUserId_ = 0L;
      chatId_ = 0L;
      chatType_ = 0;
      minServerSeq_ = 0L;
      maxServerSeq_ = 0L;
      size_ = 0;
      traceId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.xuning888.helloim.api.protobuf.message.v1.MessageServiceProto.internal_static_PullOfflineMsgRequest_descriptor;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest getDefaultInstanceForType() {
      return com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest build() {
      com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest buildPartial() {
      com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest result = new com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fromUserId_ = fromUserId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chatId_ = chatId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.chatType_ = chatType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.minServerSeq_ = minServerSeq_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxServerSeq_ = maxServerSeq_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.traceId_ = traceId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest) {
        return mergeFrom((com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest other) {
      if (other == com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest.getDefaultInstance()) return this;
      if (other.getFromUserId() != 0L) {
        setFromUserId(other.getFromUserId());
      }
      if (other.getChatId() != 0L) {
        setChatId(other.getChatId());
      }
      if (other.getChatType() != 0) {
        setChatType(other.getChatType());
      }
      if (other.getMinServerSeq() != 0L) {
        setMinServerSeq(other.getMinServerSeq());
      }
      if (other.getMaxServerSeq() != 0L) {
        setMaxServerSeq(other.getMaxServerSeq());
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (!other.getTraceId().isEmpty()) {
        traceId_ = other.traceId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fromUserId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              chatId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              chatType_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              minServerSeq_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              maxServerSeq_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              size_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              traceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long fromUserId_ ;
    /**
     * <code>int64 fromUserId = 1;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public long getFromUserId() {
      return fromUserId_;
    }
    /**
     * <code>int64 fromUserId = 1;</code>
     * @param value The fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserId(long value) {

      fromUserId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 fromUserId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fromUserId_ = 0L;
      onChanged();
      return this;
    }

    private long chatId_ ;
    /**
     * <code>int64 chatId = 2;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }
    /**
     * <code>int64 chatId = 2;</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(long value) {

      chatId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 chatId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      chatId_ = 0L;
      onChanged();
      return this;
    }

    private int chatType_ ;
    /**
     * <code>int32 chatType = 3;</code>
     * @return The chatType.
     */
    @java.lang.Override
    public int getChatType() {
      return chatType_;
    }
    /**
     * <code>int32 chatType = 3;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(int value) {

      chatType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 chatType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      chatType_ = 0;
      onChanged();
      return this;
    }

    private long minServerSeq_ ;
    /**
     * <code>int64 minServerSeq = 4;</code>
     * @return The minServerSeq.
     */
    @java.lang.Override
    public long getMinServerSeq() {
      return minServerSeq_;
    }
    /**
     * <code>int64 minServerSeq = 4;</code>
     * @param value The minServerSeq to set.
     * @return This builder for chaining.
     */
    public Builder setMinServerSeq(long value) {

      minServerSeq_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 minServerSeq = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinServerSeq() {
      bitField0_ = (bitField0_ & ~0x00000008);
      minServerSeq_ = 0L;
      onChanged();
      return this;
    }

    private long maxServerSeq_ ;
    /**
     * <code>int64 maxServerSeq = 5;</code>
     * @return The maxServerSeq.
     */
    @java.lang.Override
    public long getMaxServerSeq() {
      return maxServerSeq_;
    }
    /**
     * <code>int64 maxServerSeq = 5;</code>
     * @param value The maxServerSeq to set.
     * @return This builder for chaining.
     */
    public Builder setMaxServerSeq(long value) {

      maxServerSeq_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 maxServerSeq = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxServerSeq() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxServerSeq_ = 0L;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 6;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 6;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {

      size_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000020);
      size_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object traceId_ = "";
    /**
     * <code>string traceId = 7;</code>
     * @return The traceId.
     */
    public java.lang.String getTraceId() {
      java.lang.Object ref = traceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string traceId = 7;</code>
     * @return The bytes for traceId.
     */
    public com.google.protobuf.ByteString
        getTraceIdBytes() {
      java.lang.Object ref = traceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string traceId = 7;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string traceId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      traceId_ = getDefaultInstance().getTraceId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string traceId = 7;</code>
     * @param value The bytes for traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      traceId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PullOfflineMsgRequest)
  }

  // @@protoc_insertion_point(class_scope:PullOfflineMsgRequest)
  private static final com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest();
  }

  public static com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PullOfflineMsgRequest>
      PARSER = new com.google.protobuf.AbstractParser<PullOfflineMsgRequest>() {
    @java.lang.Override
    public PullOfflineMsgRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PullOfflineMsgRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PullOfflineMsgRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.message.v1.PullOfflineMsgRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

