// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/user/v1/user_service.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.user.v1;

public interface GetAllUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ImUser users = 1;</code>
   */
  java.util.List<com.github.xuning888.helloim.api.protobuf.common.v1.ImUser> 
      getUsersList();
  /**
   * <code>repeated .ImUser users = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ImUser getUsers(int index);
  /**
   * <code>repeated .ImUser users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .ImUser users = 1;</code>
   */
  java.util.List<? extends com.github.xuning888.helloim.api.protobuf.common.v1.ImUserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .ImUser users = 1;</code>
   */
  com.github.xuning888.helloim.api.protobuf.common.v1.ImUserOrBuilder getUsersOrBuilder(
      int index);
}
