// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/message.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

/**
 * Protobuf type {@code ChatMessage}
 */
public final class ChatMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChatMessage)
    ChatMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatMessage.newBuilder() to construct.
  private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatMessage() {
    chatIdStr_ = "";
    msgIdStr_ = "";
    msgFromStr_ = "";
    msgToStr_ = "";
    groupIdStr_ = "";
    msgContent_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.internal_static_ChatMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.internal_static_ChatMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.class, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.Builder.class);
  }

  public static final int CHATTYPE_FIELD_NUMBER = 1;
  private int chatType_ = 0;
  /**
   * <code>int32 chatType = 1;</code>
   * @return The chatType.
   */
  @java.lang.Override
  public int getChatType() {
    return chatType_;
  }

  public static final int CHATID_FIELD_NUMBER = 2;
  private long chatId_ = 0L;
  /**
   * <code>int64 chatId = 2;</code>
   * @return The chatId.
   */
  @java.lang.Override
  public long getChatId() {
    return chatId_;
  }

  public static final int CHATIDSTR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object chatIdStr_ = "";
  /**
   * <code>string chatIdStr = 3;</code>
   * @return The chatIdStr.
   */
  @java.lang.Override
  public java.lang.String getChatIdStr() {
    java.lang.Object ref = chatIdStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chatIdStr_ = s;
      return s;
    }
  }
  /**
   * <code>string chatIdStr = 3;</code>
   * @return The bytes for chatIdStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChatIdStrBytes() {
    java.lang.Object ref = chatIdStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatIdStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGID_FIELD_NUMBER = 4;
  private long msgId_ = 0L;
  /**
   * <code>int64 msgId = 4;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public long getMsgId() {
    return msgId_;
  }

  public static final int MSGIDSTR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgIdStr_ = "";
  /**
   * <code>string msgIdStr = 5;</code>
   * @return The msgIdStr.
   */
  @java.lang.Override
  public java.lang.String getMsgIdStr() {
    java.lang.Object ref = msgIdStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgIdStr_ = s;
      return s;
    }
  }
  /**
   * <code>string msgIdStr = 5;</code>
   * @return The bytes for msgIdStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgIdStrBytes() {
    java.lang.Object ref = msgIdStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgIdStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGFROM_FIELD_NUMBER = 6;
  private long msgFrom_ = 0L;
  /**
   * <code>int64 msgFrom = 6;</code>
   * @return The msgFrom.
   */
  @java.lang.Override
  public long getMsgFrom() {
    return msgFrom_;
  }

  public static final int MSGFROMSTR_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgFromStr_ = "";
  /**
   * <code>string msgFromStr = 7;</code>
   * @return The msgFromStr.
   */
  @java.lang.Override
  public java.lang.String getMsgFromStr() {
    java.lang.Object ref = msgFromStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgFromStr_ = s;
      return s;
    }
  }
  /**
   * <code>string msgFromStr = 7;</code>
   * @return The bytes for msgFromStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgFromStrBytes() {
    java.lang.Object ref = msgFromStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgFromStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROMUSERTYPE_FIELD_NUMBER = 8;
  private int fromUserType_ = 0;
  /**
   * <code>int32 fromUserType = 8;</code>
   * @return The fromUserType.
   */
  @java.lang.Override
  public int getFromUserType() {
    return fromUserType_;
  }

  public static final int MSGTO_FIELD_NUMBER = 9;
  private long msgTo_ = 0L;
  /**
   * <code>int64 msgTo = 9;</code>
   * @return The msgTo.
   */
  @java.lang.Override
  public long getMsgTo() {
    return msgTo_;
  }

  public static final int MSGTOSTR_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgToStr_ = "";
  /**
   * <code>string msgToStr = 10;</code>
   * @return The msgToStr.
   */
  @java.lang.Override
  public java.lang.String getMsgToStr() {
    java.lang.Object ref = msgToStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgToStr_ = s;
      return s;
    }
  }
  /**
   * <code>string msgToStr = 10;</code>
   * @return The bytes for msgToStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgToStrBytes() {
    java.lang.Object ref = msgToStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgToStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOUSERTYPE_FIELD_NUMBER = 11;
  private int toUserType_ = 0;
  /**
   * <code>int32 toUserType = 11;</code>
   * @return The toUserType.
   */
  @java.lang.Override
  public int getToUserType() {
    return toUserType_;
  }

  public static final int GROUPID_FIELD_NUMBER = 12;
  private long groupId_ = 0L;
  /**
   * <code>int64 groupId = 12;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public long getGroupId() {
    return groupId_;
  }

  public static final int GROUPIDSTR_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupIdStr_ = "";
  /**
   * <code>string groupIdStr = 13;</code>
   * @return The groupIdStr.
   */
  @java.lang.Override
  public java.lang.String getGroupIdStr() {
    java.lang.Object ref = groupIdStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupIdStr_ = s;
      return s;
    }
  }
  /**
   * <code>string groupIdStr = 13;</code>
   * @return The bytes for groupIdStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdStrBytes() {
    java.lang.Object ref = groupIdStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupIdStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGSEQ_FIELD_NUMBER = 14;
  private int msgSeq_ = 0;
  /**
   * <code>int32 msgSeq = 14;</code>
   * @return The msgSeq.
   */
  @java.lang.Override
  public int getMsgSeq() {
    return msgSeq_;
  }

  public static final int MSGCONTENT_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object msgContent_ = "";
  /**
   * <code>string msgContent = 15;</code>
   * @return The msgContent.
   */
  @java.lang.Override
  public java.lang.String getMsgContent() {
    java.lang.Object ref = msgContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgContent_ = s;
      return s;
    }
  }
  /**
   * <code>string msgContent = 15;</code>
   * @return The bytes for msgContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgContentBytes() {
    java.lang.Object ref = msgContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENTTYPE_FIELD_NUMBER = 16;
  private int contentType_ = 0;
  /**
   * <code>int32 contentType = 16;</code>
   * @return The contentType.
   */
  @java.lang.Override
  public int getContentType() {
    return contentType_;
  }

  public static final int CMDID_FIELD_NUMBER = 17;
  private int cmdId_ = 0;
  /**
   * <code>int32 cmdId = 17;</code>
   * @return The cmdId.
   */
  @java.lang.Override
  public int getCmdId() {
    return cmdId_;
  }

  public static final int SENDTIME_FIELD_NUMBER = 18;
  private long sendTime_ = 0L;
  /**
   * <code>int64 sendTime = 18;</code>
   * @return The sendTime.
   */
  @java.lang.Override
  public long getSendTime() {
    return sendTime_;
  }

  public static final int RECEIPTSTATUS_FIELD_NUMBER = 19;
  private int receiptStatus_ = 0;
  /**
   * <code>int32 receiptStatus = 19;</code>
   * @return The receiptStatus.
   */
  @java.lang.Override
  public int getReceiptStatus() {
    return receiptStatus_;
  }

  public static final int SERVERSEQ_FIELD_NUMBER = 20;
  private long serverSeq_ = 0L;
  /**
   * <code>int64 serverSeq = 20;</code>
   * @return The serverSeq.
   */
  @java.lang.Override
  public long getServerSeq() {
    return serverSeq_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (chatType_ != 0) {
      output.writeInt32(1, chatType_);
    }
    if (chatId_ != 0L) {
      output.writeInt64(2, chatId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatIdStr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, chatIdStr_);
    }
    if (msgId_ != 0L) {
      output.writeInt64(4, msgId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgIdStr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgIdStr_);
    }
    if (msgFrom_ != 0L) {
      output.writeInt64(6, msgFrom_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgFromStr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgFromStr_);
    }
    if (fromUserType_ != 0) {
      output.writeInt32(8, fromUserType_);
    }
    if (msgTo_ != 0L) {
      output.writeInt64(9, msgTo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgToStr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, msgToStr_);
    }
    if (toUserType_ != 0) {
      output.writeInt32(11, toUserType_);
    }
    if (groupId_ != 0L) {
      output.writeInt64(12, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupIdStr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, groupIdStr_);
    }
    if (msgSeq_ != 0) {
      output.writeInt32(14, msgSeq_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, msgContent_);
    }
    if (contentType_ != 0) {
      output.writeInt32(16, contentType_);
    }
    if (cmdId_ != 0) {
      output.writeInt32(17, cmdId_);
    }
    if (sendTime_ != 0L) {
      output.writeInt64(18, sendTime_);
    }
    if (receiptStatus_ != 0) {
      output.writeInt32(19, receiptStatus_);
    }
    if (serverSeq_ != 0L) {
      output.writeInt64(20, serverSeq_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (chatType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, chatType_);
    }
    if (chatId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, chatId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chatIdStr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, chatIdStr_);
    }
    if (msgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, msgId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgIdStr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgIdStr_);
    }
    if (msgFrom_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, msgFrom_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgFromStr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgFromStr_);
    }
    if (fromUserType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, fromUserType_);
    }
    if (msgTo_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, msgTo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgToStr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, msgToStr_);
    }
    if (toUserType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, toUserType_);
    }
    if (groupId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groupIdStr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, groupIdStr_);
    }
    if (msgSeq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, msgSeq_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, msgContent_);
    }
    if (contentType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, contentType_);
    }
    if (cmdId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, cmdId_);
    }
    if (sendTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(18, sendTime_);
    }
    if (receiptStatus_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(19, receiptStatus_);
    }
    if (serverSeq_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(20, serverSeq_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage)) {
      return super.equals(obj);
    }
    com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage other = (com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage) obj;

    if (getChatType()
        != other.getChatType()) return false;
    if (getChatId()
        != other.getChatId()) return false;
    if (!getChatIdStr()
        .equals(other.getChatIdStr())) return false;
    if (getMsgId()
        != other.getMsgId()) return false;
    if (!getMsgIdStr()
        .equals(other.getMsgIdStr())) return false;
    if (getMsgFrom()
        != other.getMsgFrom()) return false;
    if (!getMsgFromStr()
        .equals(other.getMsgFromStr())) return false;
    if (getFromUserType()
        != other.getFromUserType()) return false;
    if (getMsgTo()
        != other.getMsgTo()) return false;
    if (!getMsgToStr()
        .equals(other.getMsgToStr())) return false;
    if (getToUserType()
        != other.getToUserType()) return false;
    if (getGroupId()
        != other.getGroupId()) return false;
    if (!getGroupIdStr()
        .equals(other.getGroupIdStr())) return false;
    if (getMsgSeq()
        != other.getMsgSeq()) return false;
    if (!getMsgContent()
        .equals(other.getMsgContent())) return false;
    if (getContentType()
        != other.getContentType()) return false;
    if (getCmdId()
        != other.getCmdId()) return false;
    if (getSendTime()
        != other.getSendTime()) return false;
    if (getReceiptStatus()
        != other.getReceiptStatus()) return false;
    if (getServerSeq()
        != other.getServerSeq()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChatType();
    hash = (37 * hash) + CHATID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChatId());
    hash = (37 * hash) + CHATIDSTR_FIELD_NUMBER;
    hash = (53 * hash) + getChatIdStr().hashCode();
    hash = (37 * hash) + MSGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgId());
    hash = (37 * hash) + MSGIDSTR_FIELD_NUMBER;
    hash = (53 * hash) + getMsgIdStr().hashCode();
    hash = (37 * hash) + MSGFROM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgFrom());
    hash = (37 * hash) + MSGFROMSTR_FIELD_NUMBER;
    hash = (53 * hash) + getMsgFromStr().hashCode();
    hash = (37 * hash) + FROMUSERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFromUserType();
    hash = (37 * hash) + MSGTO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMsgTo());
    hash = (37 * hash) + MSGTOSTR_FIELD_NUMBER;
    hash = (53 * hash) + getMsgToStr().hashCode();
    hash = (37 * hash) + TOUSERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getToUserType();
    hash = (37 * hash) + GROUPID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGroupId());
    hash = (37 * hash) + GROUPIDSTR_FIELD_NUMBER;
    hash = (53 * hash) + getGroupIdStr().hashCode();
    hash = (37 * hash) + MSGSEQ_FIELD_NUMBER;
    hash = (53 * hash) + getMsgSeq();
    hash = (37 * hash) + MSGCONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getMsgContent().hashCode();
    hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getContentType();
    hash = (37 * hash) + CMDID_FIELD_NUMBER;
    hash = (53 * hash) + getCmdId();
    hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSendTime());
    hash = (37 * hash) + RECEIPTSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getReceiptStatus();
    hash = (37 * hash) + SERVERSEQ_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getServerSeq());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChatMessage)
      com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.internal_static_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.internal_static_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.class, com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.Builder.class);
    }

    // Construct using com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      chatType_ = 0;
      chatId_ = 0L;
      chatIdStr_ = "";
      msgId_ = 0L;
      msgIdStr_ = "";
      msgFrom_ = 0L;
      msgFromStr_ = "";
      fromUserType_ = 0;
      msgTo_ = 0L;
      msgToStr_ = "";
      toUserType_ = 0;
      groupId_ = 0L;
      groupIdStr_ = "";
      msgSeq_ = 0;
      msgContent_ = "";
      contentType_ = 0;
      cmdId_ = 0;
      sendTime_ = 0L;
      receiptStatus_ = 0;
      serverSeq_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessageProto.internal_static_ChatMessage_descriptor;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getDefaultInstanceForType() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage build() {
      com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage buildPartial() {
      com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage result = new com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.chatType_ = chatType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chatId_ = chatId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.chatIdStr_ = chatIdStr_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.msgId_ = msgId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.msgIdStr_ = msgIdStr_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.msgFrom_ = msgFrom_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.msgFromStr_ = msgFromStr_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.fromUserType_ = fromUserType_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.msgTo_ = msgTo_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.msgToStr_ = msgToStr_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.toUserType_ = toUserType_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.groupIdStr_ = groupIdStr_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.msgSeq_ = msgSeq_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.msgContent_ = msgContent_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.contentType_ = contentType_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.cmdId_ = cmdId_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.sendTime_ = sendTime_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.receiptStatus_ = receiptStatus_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.serverSeq_ = serverSeq_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage) {
        return mergeFrom((com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage other) {
      if (other == com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage.getDefaultInstance()) return this;
      if (other.getChatType() != 0) {
        setChatType(other.getChatType());
      }
      if (other.getChatId() != 0L) {
        setChatId(other.getChatId());
      }
      if (!other.getChatIdStr().isEmpty()) {
        chatIdStr_ = other.chatIdStr_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getMsgId() != 0L) {
        setMsgId(other.getMsgId());
      }
      if (!other.getMsgIdStr().isEmpty()) {
        msgIdStr_ = other.msgIdStr_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getMsgFrom() != 0L) {
        setMsgFrom(other.getMsgFrom());
      }
      if (!other.getMsgFromStr().isEmpty()) {
        msgFromStr_ = other.msgFromStr_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getFromUserType() != 0) {
        setFromUserType(other.getFromUserType());
      }
      if (other.getMsgTo() != 0L) {
        setMsgTo(other.getMsgTo());
      }
      if (!other.getMsgToStr().isEmpty()) {
        msgToStr_ = other.msgToStr_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getToUserType() != 0) {
        setToUserType(other.getToUserType());
      }
      if (other.getGroupId() != 0L) {
        setGroupId(other.getGroupId());
      }
      if (!other.getGroupIdStr().isEmpty()) {
        groupIdStr_ = other.groupIdStr_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getMsgSeq() != 0) {
        setMsgSeq(other.getMsgSeq());
      }
      if (!other.getMsgContent().isEmpty()) {
        msgContent_ = other.msgContent_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      if (other.getContentType() != 0) {
        setContentType(other.getContentType());
      }
      if (other.getCmdId() != 0) {
        setCmdId(other.getCmdId());
      }
      if (other.getSendTime() != 0L) {
        setSendTime(other.getSendTime());
      }
      if (other.getReceiptStatus() != 0) {
        setReceiptStatus(other.getReceiptStatus());
      }
      if (other.getServerSeq() != 0L) {
        setServerSeq(other.getServerSeq());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              chatType_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              chatId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              chatIdStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              msgId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              msgIdStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              msgFrom_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              msgFromStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              fromUserType_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              msgTo_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              msgToStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              toUserType_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              groupId_ = input.readInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 106: {
              groupIdStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              msgSeq_ = input.readInt32();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 122: {
              msgContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            case 128: {
              contentType_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            case 136: {
              cmdId_ = input.readInt32();
              bitField0_ |= 0x00010000;
              break;
            } // case 136
            case 144: {
              sendTime_ = input.readInt64();
              bitField0_ |= 0x00020000;
              break;
            } // case 144
            case 152: {
              receiptStatus_ = input.readInt32();
              bitField0_ |= 0x00040000;
              break;
            } // case 152
            case 160: {
              serverSeq_ = input.readInt64();
              bitField0_ |= 0x00080000;
              break;
            } // case 160
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int chatType_ ;
    /**
     * <code>int32 chatType = 1;</code>
     * @return The chatType.
     */
    @java.lang.Override
    public int getChatType() {
      return chatType_;
    }
    /**
     * <code>int32 chatType = 1;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(int value) {

      chatType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 chatType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      chatType_ = 0;
      onChanged();
      return this;
    }

    private long chatId_ ;
    /**
     * <code>int64 chatId = 2;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }
    /**
     * <code>int64 chatId = 2;</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(long value) {

      chatId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 chatId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      chatId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object chatIdStr_ = "";
    /**
     * <code>string chatIdStr = 3;</code>
     * @return The chatIdStr.
     */
    public java.lang.String getChatIdStr() {
      java.lang.Object ref = chatIdStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chatIdStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chatIdStr = 3;</code>
     * @return The bytes for chatIdStr.
     */
    public com.google.protobuf.ByteString
        getChatIdStrBytes() {
      java.lang.Object ref = chatIdStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatIdStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chatIdStr = 3;</code>
     * @param value The chatIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setChatIdStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      chatIdStr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string chatIdStr = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatIdStr() {
      chatIdStr_ = getDefaultInstance().getChatIdStr();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string chatIdStr = 3;</code>
     * @param value The bytes for chatIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setChatIdStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      chatIdStr_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long msgId_ ;
    /**
     * <code>int64 msgId = 4;</code>
     * @return The msgId.
     */
    @java.lang.Override
    public long getMsgId() {
      return msgId_;
    }
    /**
     * <code>int64 msgId = 4;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(long value) {

      msgId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 msgId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      msgId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object msgIdStr_ = "";
    /**
     * <code>string msgIdStr = 5;</code>
     * @return The msgIdStr.
     */
    public java.lang.String getMsgIdStr() {
      java.lang.Object ref = msgIdStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgIdStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgIdStr = 5;</code>
     * @return The bytes for msgIdStr.
     */
    public com.google.protobuf.ByteString
        getMsgIdStrBytes() {
      java.lang.Object ref = msgIdStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgIdStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgIdStr = 5;</code>
     * @param value The msgIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgIdStr_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string msgIdStr = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgIdStr() {
      msgIdStr_ = getDefaultInstance().getMsgIdStr();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string msgIdStr = 5;</code>
     * @param value The bytes for msgIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgIdStr_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long msgFrom_ ;
    /**
     * <code>int64 msgFrom = 6;</code>
     * @return The msgFrom.
     */
    @java.lang.Override
    public long getMsgFrom() {
      return msgFrom_;
    }
    /**
     * <code>int64 msgFrom = 6;</code>
     * @param value The msgFrom to set.
     * @return This builder for chaining.
     */
    public Builder setMsgFrom(long value) {

      msgFrom_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 msgFrom = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgFrom() {
      bitField0_ = (bitField0_ & ~0x00000020);
      msgFrom_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object msgFromStr_ = "";
    /**
     * <code>string msgFromStr = 7;</code>
     * @return The msgFromStr.
     */
    public java.lang.String getMsgFromStr() {
      java.lang.Object ref = msgFromStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgFromStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgFromStr = 7;</code>
     * @return The bytes for msgFromStr.
     */
    public com.google.protobuf.ByteString
        getMsgFromStrBytes() {
      java.lang.Object ref = msgFromStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgFromStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgFromStr = 7;</code>
     * @param value The msgFromStr to set.
     * @return This builder for chaining.
     */
    public Builder setMsgFromStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgFromStr_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string msgFromStr = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgFromStr() {
      msgFromStr_ = getDefaultInstance().getMsgFromStr();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string msgFromStr = 7;</code>
     * @param value The bytes for msgFromStr to set.
     * @return This builder for chaining.
     */
    public Builder setMsgFromStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgFromStr_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int fromUserType_ ;
    /**
     * <code>int32 fromUserType = 8;</code>
     * @return The fromUserType.
     */
    @java.lang.Override
    public int getFromUserType() {
      return fromUserType_;
    }
    /**
     * <code>int32 fromUserType = 8;</code>
     * @param value The fromUserType to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserType(int value) {

      fromUserType_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 fromUserType = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUserType() {
      bitField0_ = (bitField0_ & ~0x00000080);
      fromUserType_ = 0;
      onChanged();
      return this;
    }

    private long msgTo_ ;
    /**
     * <code>int64 msgTo = 9;</code>
     * @return The msgTo.
     */
    @java.lang.Override
    public long getMsgTo() {
      return msgTo_;
    }
    /**
     * <code>int64 msgTo = 9;</code>
     * @param value The msgTo to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTo(long value) {

      msgTo_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 msgTo = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgTo() {
      bitField0_ = (bitField0_ & ~0x00000100);
      msgTo_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object msgToStr_ = "";
    /**
     * <code>string msgToStr = 10;</code>
     * @return The msgToStr.
     */
    public java.lang.String getMsgToStr() {
      java.lang.Object ref = msgToStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgToStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgToStr = 10;</code>
     * @return The bytes for msgToStr.
     */
    public com.google.protobuf.ByteString
        getMsgToStrBytes() {
      java.lang.Object ref = msgToStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgToStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgToStr = 10;</code>
     * @param value The msgToStr to set.
     * @return This builder for chaining.
     */
    public Builder setMsgToStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgToStr_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string msgToStr = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgToStr() {
      msgToStr_ = getDefaultInstance().getMsgToStr();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string msgToStr = 10;</code>
     * @param value The bytes for msgToStr to set.
     * @return This builder for chaining.
     */
    public Builder setMsgToStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgToStr_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private int toUserType_ ;
    /**
     * <code>int32 toUserType = 11;</code>
     * @return The toUserType.
     */
    @java.lang.Override
    public int getToUserType() {
      return toUserType_;
    }
    /**
     * <code>int32 toUserType = 11;</code>
     * @param value The toUserType to set.
     * @return This builder for chaining.
     */
    public Builder setToUserType(int value) {

      toUserType_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 toUserType = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearToUserType() {
      bitField0_ = (bitField0_ & ~0x00000400);
      toUserType_ = 0;
      onChanged();
      return this;
    }

    private long groupId_ ;
    /**
     * <code>int64 groupId = 12;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public long getGroupId() {
      return groupId_;
    }
    /**
     * <code>int64 groupId = 12;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(long value) {

      groupId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>int64 groupId = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      bitField0_ = (bitField0_ & ~0x00000800);
      groupId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object groupIdStr_ = "";
    /**
     * <code>string groupIdStr = 13;</code>
     * @return The groupIdStr.
     */
    public java.lang.String getGroupIdStr() {
      java.lang.Object ref = groupIdStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupIdStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string groupIdStr = 13;</code>
     * @return The bytes for groupIdStr.
     */
    public com.google.protobuf.ByteString
        getGroupIdStrBytes() {
      java.lang.Object ref = groupIdStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupIdStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string groupIdStr = 13;</code>
     * @param value The groupIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupIdStr_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string groupIdStr = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupIdStr() {
      groupIdStr_ = getDefaultInstance().getGroupIdStr();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string groupIdStr = 13;</code>
     * @param value The bytes for groupIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupIdStr_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private int msgSeq_ ;
    /**
     * <code>int32 msgSeq = 14;</code>
     * @return The msgSeq.
     */
    @java.lang.Override
    public int getMsgSeq() {
      return msgSeq_;
    }
    /**
     * <code>int32 msgSeq = 14;</code>
     * @param value The msgSeq to set.
     * @return This builder for chaining.
     */
    public Builder setMsgSeq(int value) {

      msgSeq_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 msgSeq = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgSeq() {
      bitField0_ = (bitField0_ & ~0x00002000);
      msgSeq_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msgContent_ = "";
    /**
     * <code>string msgContent = 15;</code>
     * @return The msgContent.
     */
    public java.lang.String getMsgContent() {
      java.lang.Object ref = msgContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string msgContent = 15;</code>
     * @return The bytes for msgContent.
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string msgContent = 15;</code>
     * @param value The msgContent to set.
     * @return This builder for chaining.
     */
    public Builder setMsgContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      msgContent_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string msgContent = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgContent() {
      msgContent_ = getDefaultInstance().getMsgContent();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string msgContent = 15;</code>
     * @param value The bytes for msgContent to set.
     * @return This builder for chaining.
     */
    public Builder setMsgContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      msgContent_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    private int contentType_ ;
    /**
     * <code>int32 contentType = 16;</code>
     * @return The contentType.
     */
    @java.lang.Override
    public int getContentType() {
      return contentType_;
    }
    /**
     * <code>int32 contentType = 16;</code>
     * @param value The contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentType(int value) {

      contentType_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 contentType = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentType() {
      bitField0_ = (bitField0_ & ~0x00008000);
      contentType_ = 0;
      onChanged();
      return this;
    }

    private int cmdId_ ;
    /**
     * <code>int32 cmdId = 17;</code>
     * @return The cmdId.
     */
    @java.lang.Override
    public int getCmdId() {
      return cmdId_;
    }
    /**
     * <code>int32 cmdId = 17;</code>
     * @param value The cmdId to set.
     * @return This builder for chaining.
     */
    public Builder setCmdId(int value) {

      cmdId_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cmdId = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmdId() {
      bitField0_ = (bitField0_ & ~0x00010000);
      cmdId_ = 0;
      onChanged();
      return this;
    }

    private long sendTime_ ;
    /**
     * <code>int64 sendTime = 18;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }
    /**
     * <code>int64 sendTime = 18;</code>
     * @param value The sendTime to set.
     * @return This builder for chaining.
     */
    public Builder setSendTime(long value) {

      sendTime_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sendTime = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearSendTime() {
      bitField0_ = (bitField0_ & ~0x00020000);
      sendTime_ = 0L;
      onChanged();
      return this;
    }

    private int receiptStatus_ ;
    /**
     * <code>int32 receiptStatus = 19;</code>
     * @return The receiptStatus.
     */
    @java.lang.Override
    public int getReceiptStatus() {
      return receiptStatus_;
    }
    /**
     * <code>int32 receiptStatus = 19;</code>
     * @param value The receiptStatus to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptStatus(int value) {

      receiptStatus_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }
    /**
     * <code>int32 receiptStatus = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiptStatus() {
      bitField0_ = (bitField0_ & ~0x00040000);
      receiptStatus_ = 0;
      onChanged();
      return this;
    }

    private long serverSeq_ ;
    /**
     * <code>int64 serverSeq = 20;</code>
     * @return The serverSeq.
     */
    @java.lang.Override
    public long getServerSeq() {
      return serverSeq_;
    }
    /**
     * <code>int64 serverSeq = 20;</code>
     * @param value The serverSeq to set.
     * @return This builder for chaining.
     */
    public Builder setServerSeq(long value) {

      serverSeq_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }
    /**
     * <code>int64 serverSeq = 20;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerSeq() {
      bitField0_ = (bitField0_ & ~0x00080000);
      serverSeq_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChatMessage)
  }

  // @@protoc_insertion_point(class_scope:ChatMessage)
  private static final com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage();
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatMessage>
      PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
    @java.lang.Override
    public ChatMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.common.v1.ChatMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

