// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/message.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

public final class ChatMessageProto {
  private ChatMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033api/common/v1/message.proto\"\374\002\n\013ChatMe" +
      "ssage\022\020\n\010chatType\030\001 \001(\005\022\016\n\006chatId\030\002 \001(\003\022" +
      "\021\n\tchatIdStr\030\003 \001(\t\022\r\n\005msgId\030\004 \001(\003\022\020\n\010msg" +
      "IdStr\030\005 \001(\t\022\017\n\007msgFrom\030\006 \001(\003\022\022\n\nmsgFromS" +
      "tr\030\007 \001(\t\022\024\n\014fromUserType\030\010 \001(\005\022\r\n\005msgTo\030" +
      "\t \001(\003\022\020\n\010msgToStr\030\n \001(\t\022\022\n\ntoUserType\030\013 " +
      "\001(\005\022\017\n\007groupId\030\014 \001(\003\022\022\n\ngroupIdStr\030\r \001(\t" +
      "\022\016\n\006msgSeq\030\016 \001(\005\022\022\n\nmsgContent\030\017 \001(\t\022\023\n\013" +
      "contentType\030\020 \001(\005\022\r\n\005cmdId\030\021 \001(\005\022\020\n\010send" +
      "Time\030\022 \001(\003\022\025\n\rreceiptStatus\030\023 \001(\005\022\021\n\tser" +
      "verSeq\030\024 \001(\003BI\n3com.github.xuning888.hel" +
      "loim.api.protobuf.common.v1B\020ChatMessage" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMessage_descriptor,
        new java.lang.String[] { "ChatType", "ChatId", "ChatIdStr", "MsgId", "MsgIdStr", "MsgFrom", "MsgFromStr", "FromUserType", "MsgTo", "MsgToStr", "ToUserType", "GroupId", "GroupIdStr", "MsgSeq", "MsgContent", "ContentType", "CmdId", "SendTime", "ReceiptStatus", "ServerSeq", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
