// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/common.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032api/common/v1/common.proto\032\037google/pro" +
      "tobuf/timestamp.proto\"\355\001\n\006ImUser\022\016\n\006user" +
      "Id\030\001 \001(\003\022\020\n\010userType\030\002 \001(\005\022\020\n\010userName\030\003" +
      " \001(\t\022\014\n\004icon\030\004 \001(\t\022\016\n\006mobile\030\005 \001(\t\022\020\n\010de" +
      "viceId\030\006 \001(\t\022\r\n\005extra\030\007 \001(\t\022\022\n\nuserStatu" +
      "s\030\010 \001(\005\022-\n\tcreatedAt\030\t \001(\0132\032.google.prot" +
      "obuf.Timestamp\022-\n\tupdatedAt\030\n \001(\0132\032.goog" +
      "le.protobuf.TimestampBD\n3com.github.xuni" +
      "ng888.helloim.api.protobuf.common.v1B\013Co" +
      "mmonProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ImUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImUser_descriptor,
        new java.lang.String[] { "UserId", "UserType", "UserName", "Icon", "Mobile", "DeviceId", "Extra", "UserStatus", "CreatedAt", "UpdatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
