// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/frame.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

public final class FrameProto {
  private FrameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FramePb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FramePb_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeaderPb_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeaderPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031api/common/v1/frame.proto\"2\n\007FramePb\022\031" +
      "\n\006header\030\001 \001(\0132\t.HeaderPb\022\014\n\004body\030\002 \001(\014\"" +
      "]\n\010HeaderPb\022\024\n\014HeaderLength\030\001 \001(\005\022\013\n\003req" +
      "\030\002 \001(\005\022\013\n\003seq\030\003 \001(\005\022\r\n\005cmdId\030\004 \001(\005\022\022\n\nbo" +
      "dyLength\030\005 \001(\005BC\n3com.github.xuning888.h" +
      "elloim.api.protobuf.common.v1B\nFrameProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FramePb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FramePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FramePb_descriptor,
        new java.lang.String[] { "Header", "Body", });
    internal_static_HeaderPb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeaderPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeaderPb_descriptor,
        new java.lang.String[] { "HeaderLength", "Req", "Seq", "CmdId", "BodyLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
