// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/frame.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

/**
 * Protobuf type {@code HeaderPb}
 */
public final class HeaderPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HeaderPb)
    HeaderPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeaderPb.newBuilder() to construct.
  private HeaderPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeaderPb() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeaderPb();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.xuning888.helloim.api.protobuf.common.v1.FrameProto.internal_static_HeaderPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.xuning888.helloim.api.protobuf.common.v1.FrameProto.internal_static_HeaderPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb.class, com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb.Builder.class);
  }

  public static final int HEADERLENGTH_FIELD_NUMBER = 1;
  private int headerLength_ = 0;
  /**
   * <pre>
   * 实际存储int8
   * </pre>
   *
   * <code>int32 HeaderLength = 1;</code>
   * @return The headerLength.
   */
  @java.lang.Override
  public int getHeaderLength() {
    return headerLength_;
  }

  public static final int REQ_FIELD_NUMBER = 2;
  private int req_ = 0;
  /**
   * <pre>
   * 实际存储int8
   * </pre>
   *
   * <code>int32 req = 2;</code>
   * @return The req.
   */
  @java.lang.Override
  public int getReq() {
    return req_;
  }

  public static final int SEQ_FIELD_NUMBER = 3;
  private int seq_ = 0;
  /**
   * <pre>
   * 实际存储int32
   * </pre>
   *
   * <code>int32 seq = 3;</code>
   * @return The seq.
   */
  @java.lang.Override
  public int getSeq() {
    return seq_;
  }

  public static final int CMDID_FIELD_NUMBER = 4;
  private int cmdId_ = 0;
  /**
   * <pre>
   * 实际存储int32
   * </pre>
   *
   * <code>int32 cmdId = 4;</code>
   * @return The cmdId.
   */
  @java.lang.Override
  public int getCmdId() {
    return cmdId_;
  }

  public static final int BODYLENGTH_FIELD_NUMBER = 5;
  private int bodyLength_ = 0;
  /**
   * <pre>
   * 实际存储int32
   * </pre>
   *
   * <code>int32 bodyLength = 5;</code>
   * @return The bodyLength.
   */
  @java.lang.Override
  public int getBodyLength() {
    return bodyLength_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (headerLength_ != 0) {
      output.writeInt32(1, headerLength_);
    }
    if (req_ != 0) {
      output.writeInt32(2, req_);
    }
    if (seq_ != 0) {
      output.writeInt32(3, seq_);
    }
    if (cmdId_ != 0) {
      output.writeInt32(4, cmdId_);
    }
    if (bodyLength_ != 0) {
      output.writeInt32(5, bodyLength_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (headerLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, headerLength_);
    }
    if (req_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, req_);
    }
    if (seq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, seq_);
    }
    if (cmdId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, cmdId_);
    }
    if (bodyLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, bodyLength_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb)) {
      return super.equals(obj);
    }
    com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb other = (com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb) obj;

    if (getHeaderLength()
        != other.getHeaderLength()) return false;
    if (getReq()
        != other.getReq()) return false;
    if (getSeq()
        != other.getSeq()) return false;
    if (getCmdId()
        != other.getCmdId()) return false;
    if (getBodyLength()
        != other.getBodyLength()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEADERLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getHeaderLength();
    hash = (37 * hash) + REQ_FIELD_NUMBER;
    hash = (53 * hash) + getReq();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + getSeq();
    hash = (37 * hash) + CMDID_FIELD_NUMBER;
    hash = (53 * hash) + getCmdId();
    hash = (37 * hash) + BODYLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getBodyLength();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HeaderPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HeaderPb)
      com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.FrameProto.internal_static_HeaderPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.FrameProto.internal_static_HeaderPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb.class, com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb.Builder.class);
    }

    // Construct using com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      headerLength_ = 0;
      req_ = 0;
      seq_ = 0;
      cmdId_ = 0;
      bodyLength_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.FrameProto.internal_static_HeaderPb_descriptor;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb getDefaultInstanceForType() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb build() {
      com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb buildPartial() {
      com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb result = new com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.headerLength_ = headerLength_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.req_ = req_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.seq_ = seq_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cmdId_ = cmdId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bodyLength_ = bodyLength_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb) {
        return mergeFrom((com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb other) {
      if (other == com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb.getDefaultInstance()) return this;
      if (other.getHeaderLength() != 0) {
        setHeaderLength(other.getHeaderLength());
      }
      if (other.getReq() != 0) {
        setReq(other.getReq());
      }
      if (other.getSeq() != 0) {
        setSeq(other.getSeq());
      }
      if (other.getCmdId() != 0) {
        setCmdId(other.getCmdId());
      }
      if (other.getBodyLength() != 0) {
        setBodyLength(other.getBodyLength());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              headerLength_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              req_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              seq_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              cmdId_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              bodyLength_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int headerLength_ ;
    /**
     * <pre>
     * 实际存储int8
     * </pre>
     *
     * <code>int32 HeaderLength = 1;</code>
     * @return The headerLength.
     */
    @java.lang.Override
    public int getHeaderLength() {
      return headerLength_;
    }
    /**
     * <pre>
     * 实际存储int8
     * </pre>
     *
     * <code>int32 HeaderLength = 1;</code>
     * @param value The headerLength to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderLength(int value) {

      headerLength_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际存储int8
     * </pre>
     *
     * <code>int32 HeaderLength = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeaderLength() {
      bitField0_ = (bitField0_ & ~0x00000001);
      headerLength_ = 0;
      onChanged();
      return this;
    }

    private int req_ ;
    /**
     * <pre>
     * 实际存储int8
     * </pre>
     *
     * <code>int32 req = 2;</code>
     * @return The req.
     */
    @java.lang.Override
    public int getReq() {
      return req_;
    }
    /**
     * <pre>
     * 实际存储int8
     * </pre>
     *
     * <code>int32 req = 2;</code>
     * @param value The req to set.
     * @return This builder for chaining.
     */
    public Builder setReq(int value) {

      req_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际存储int8
     * </pre>
     *
     * <code>int32 req = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReq() {
      bitField0_ = (bitField0_ & ~0x00000002);
      req_ = 0;
      onChanged();
      return this;
    }

    private int seq_ ;
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 seq = 3;</code>
     * @return The seq.
     */
    @java.lang.Override
    public int getSeq() {
      return seq_;
    }
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 seq = 3;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(int value) {

      seq_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 seq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      bitField0_ = (bitField0_ & ~0x00000004);
      seq_ = 0;
      onChanged();
      return this;
    }

    private int cmdId_ ;
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 cmdId = 4;</code>
     * @return The cmdId.
     */
    @java.lang.Override
    public int getCmdId() {
      return cmdId_;
    }
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 cmdId = 4;</code>
     * @param value The cmdId to set.
     * @return This builder for chaining.
     */
    public Builder setCmdId(int value) {

      cmdId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 cmdId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmdId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cmdId_ = 0;
      onChanged();
      return this;
    }

    private int bodyLength_ ;
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 bodyLength = 5;</code>
     * @return The bodyLength.
     */
    @java.lang.Override
    public int getBodyLength() {
      return bodyLength_;
    }
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 bodyLength = 5;</code>
     * @param value The bodyLength to set.
     * @return This builder for chaining.
     */
    public Builder setBodyLength(int value) {

      bodyLength_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 实际存储int32
     * </pre>
     *
     * <code>int32 bodyLength = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBodyLength() {
      bitField0_ = (bitField0_ & ~0x00000010);
      bodyLength_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HeaderPb)
  }

  // @@protoc_insertion_point(class_scope:HeaderPb)
  private static final com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb();
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeaderPb>
      PARSER = new com.google.protobuf.AbstractParser<HeaderPb>() {
    @java.lang.Override
    public HeaderPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HeaderPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeaderPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.common.v1.HeaderPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

