// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/chat.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

/**
 * Protobuf type {@code ImChat}
 */
public final class ImChat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ImChat)
    ImChatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImChat.newBuilder() to construct.
  private ImChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImChat() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImChat();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.internal_static_ImChat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.internal_static_ImChat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.class, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int CHATID_FIELD_NUMBER = 2;
  private long chatId_ = 0L;
  /**
   * <code>int64 chatId = 2;</code>
   * @return The chatId.
   */
  @java.lang.Override
  public long getChatId() {
    return chatId_;
  }

  public static final int CHATTYPE_FIELD_NUMBER = 3;
  private int chatType_ = 0;
  /**
   * <code>int32 chatType = 3;</code>
   * @return The chatType.
   */
  @java.lang.Override
  public int getChatType() {
    return chatType_;
  }

  public static final int CHATTOP_FIELD_NUMBER = 4;
  private boolean chatTop_ = false;
  /**
   * <code>bool chatTop = 4;</code>
   * @return The chatTop.
   */
  @java.lang.Override
  public boolean getChatTop() {
    return chatTop_;
  }

  public static final int CHATMUTE_FIELD_NUMBER = 5;
  private boolean chatMute_ = false;
  /**
   * <code>bool chatMute = 5;</code>
   * @return The chatMute.
   */
  @java.lang.Override
  public boolean getChatMute() {
    return chatMute_;
  }

  public static final int CHATDEL_FIELD_NUMBER = 6;
  private boolean chatDel_ = false;
  /**
   * <code>bool chatDel = 6;</code>
   * @return The chatDel.
   */
  @java.lang.Override
  public boolean getChatDel() {
    return chatDel_;
  }

  public static final int UPDATETIMESTAMP_FIELD_NUMBER = 7;
  private long updateTimestamp_ = 0L;
  /**
   * <code>int64 updateTimestamp = 7;</code>
   * @return The updateTimestamp.
   */
  @java.lang.Override
  public long getUpdateTimestamp() {
    return updateTimestamp_;
  }

  public static final int DELTIMESTAMP_FIELD_NUMBER = 8;
  private long delTimestamp_ = 0L;
  /**
   * <code>int64 delTimestamp = 8;</code>
   * @return The delTimestamp.
   */
  @java.lang.Override
  public long getDelTimestamp() {
    return delTimestamp_;
  }

  public static final int LASTREADMSGID_FIELD_NUMBER = 9;
  private long lastReadMsgId_ = 0L;
  /**
   * <code>int64 lastReadMsgId = 9;</code>
   * @return The lastReadMsgId.
   */
  @java.lang.Override
  public long getLastReadMsgId() {
    return lastReadMsgId_;
  }

  public static final int SUBSTATUS_FIELD_NUMBER = 10;
  private int subStatus_ = 0;
  /**
   * <code>int32 subStatus = 10;</code>
   * @return The subStatus.
   */
  @java.lang.Override
  public int getSubStatus() {
    return subStatus_;
  }

  public static final int JOINGROUPTIMESTAMP_FIELD_NUMBER = 11;
  private long joinGroupTimestamp_ = 0L;
  /**
   * <code>int64 joinGroupTimestamp = 11;</code>
   * @return The joinGroupTimestamp.
   */
  @java.lang.Override
  public long getJoinGroupTimestamp() {
    return joinGroupTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (chatId_ != 0L) {
      output.writeInt64(2, chatId_);
    }
    if (chatType_ != 0) {
      output.writeInt32(3, chatType_);
    }
    if (chatTop_ != false) {
      output.writeBool(4, chatTop_);
    }
    if (chatMute_ != false) {
      output.writeBool(5, chatMute_);
    }
    if (chatDel_ != false) {
      output.writeBool(6, chatDel_);
    }
    if (updateTimestamp_ != 0L) {
      output.writeInt64(7, updateTimestamp_);
    }
    if (delTimestamp_ != 0L) {
      output.writeInt64(8, delTimestamp_);
    }
    if (lastReadMsgId_ != 0L) {
      output.writeInt64(9, lastReadMsgId_);
    }
    if (subStatus_ != 0) {
      output.writeInt32(10, subStatus_);
    }
    if (joinGroupTimestamp_ != 0L) {
      output.writeInt64(11, joinGroupTimestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (chatId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, chatId_);
    }
    if (chatType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, chatType_);
    }
    if (chatTop_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, chatTop_);
    }
    if (chatMute_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, chatMute_);
    }
    if (chatDel_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, chatDel_);
    }
    if (updateTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, updateTimestamp_);
    }
    if (delTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, delTimestamp_);
    }
    if (lastReadMsgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, lastReadMsgId_);
    }
    if (subStatus_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, subStatus_);
    }
    if (joinGroupTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, joinGroupTimestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.xuning888.helloim.api.protobuf.common.v1.ImChat)) {
      return super.equals(obj);
    }
    com.github.xuning888.helloim.api.protobuf.common.v1.ImChat other = (com.github.xuning888.helloim.api.protobuf.common.v1.ImChat) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getChatId()
        != other.getChatId()) return false;
    if (getChatType()
        != other.getChatType()) return false;
    if (getChatTop()
        != other.getChatTop()) return false;
    if (getChatMute()
        != other.getChatMute()) return false;
    if (getChatDel()
        != other.getChatDel()) return false;
    if (getUpdateTimestamp()
        != other.getUpdateTimestamp()) return false;
    if (getDelTimestamp()
        != other.getDelTimestamp()) return false;
    if (getLastReadMsgId()
        != other.getLastReadMsgId()) return false;
    if (getSubStatus()
        != other.getSubStatus()) return false;
    if (getJoinGroupTimestamp()
        != other.getJoinGroupTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + CHATID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChatId());
    hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChatType();
    hash = (37 * hash) + CHATTOP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getChatTop());
    hash = (37 * hash) + CHATMUTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getChatMute());
    hash = (37 * hash) + CHATDEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getChatDel());
    hash = (37 * hash) + UPDATETIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateTimestamp());
    hash = (37 * hash) + DELTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDelTimestamp());
    hash = (37 * hash) + LASTREADMSGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastReadMsgId());
    hash = (37 * hash) + SUBSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getSubStatus();
    hash = (37 * hash) + JOINGROUPTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getJoinGroupTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.xuning888.helloim.api.protobuf.common.v1.ImChat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ImChat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ImChat)
      com.github.xuning888.helloim.api.protobuf.common.v1.ImChatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.internal_static_ImChat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.internal_static_ImChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.class, com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.Builder.class);
    }

    // Construct using com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      chatId_ = 0L;
      chatType_ = 0;
      chatTop_ = false;
      chatMute_ = false;
      chatDel_ = false;
      updateTimestamp_ = 0L;
      delTimestamp_ = 0L;
      lastReadMsgId_ = 0L;
      subStatus_ = 0;
      joinGroupTimestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ImChatProto.internal_static_ImChat_descriptor;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat getDefaultInstanceForType() {
      return com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat build() {
      com.github.xuning888.helloim.api.protobuf.common.v1.ImChat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat buildPartial() {
      com.github.xuning888.helloim.api.protobuf.common.v1.ImChat result = new com.github.xuning888.helloim.api.protobuf.common.v1.ImChat(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.xuning888.helloim.api.protobuf.common.v1.ImChat result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chatId_ = chatId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.chatType_ = chatType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.chatTop_ = chatTop_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.chatMute_ = chatMute_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.chatDel_ = chatDel_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.updateTimestamp_ = updateTimestamp_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.delTimestamp_ = delTimestamp_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.lastReadMsgId_ = lastReadMsgId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.subStatus_ = subStatus_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.joinGroupTimestamp_ = joinGroupTimestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.xuning888.helloim.api.protobuf.common.v1.ImChat) {
        return mergeFrom((com.github.xuning888.helloim.api.protobuf.common.v1.ImChat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.xuning888.helloim.api.protobuf.common.v1.ImChat other) {
      if (other == com.github.xuning888.helloim.api.protobuf.common.v1.ImChat.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getChatId() != 0L) {
        setChatId(other.getChatId());
      }
      if (other.getChatType() != 0) {
        setChatType(other.getChatType());
      }
      if (other.getChatTop() != false) {
        setChatTop(other.getChatTop());
      }
      if (other.getChatMute() != false) {
        setChatMute(other.getChatMute());
      }
      if (other.getChatDel() != false) {
        setChatDel(other.getChatDel());
      }
      if (other.getUpdateTimestamp() != 0L) {
        setUpdateTimestamp(other.getUpdateTimestamp());
      }
      if (other.getDelTimestamp() != 0L) {
        setDelTimestamp(other.getDelTimestamp());
      }
      if (other.getLastReadMsgId() != 0L) {
        setLastReadMsgId(other.getLastReadMsgId());
      }
      if (other.getSubStatus() != 0) {
        setSubStatus(other.getSubStatus());
      }
      if (other.getJoinGroupTimestamp() != 0L) {
        setJoinGroupTimestamp(other.getJoinGroupTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              chatId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              chatType_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              chatTop_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              chatMute_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              chatDel_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              updateTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              delTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              lastReadMsgId_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              subStatus_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              joinGroupTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long chatId_ ;
    /**
     * <code>int64 chatId = 2;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }
    /**
     * <code>int64 chatId = 2;</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(long value) {

      chatId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 chatId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      chatId_ = 0L;
      onChanged();
      return this;
    }

    private int chatType_ ;
    /**
     * <code>int32 chatType = 3;</code>
     * @return The chatType.
     */
    @java.lang.Override
    public int getChatType() {
      return chatType_;
    }
    /**
     * <code>int32 chatType = 3;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(int value) {

      chatType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 chatType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      chatType_ = 0;
      onChanged();
      return this;
    }

    private boolean chatTop_ ;
    /**
     * <code>bool chatTop = 4;</code>
     * @return The chatTop.
     */
    @java.lang.Override
    public boolean getChatTop() {
      return chatTop_;
    }
    /**
     * <code>bool chatTop = 4;</code>
     * @param value The chatTop to set.
     * @return This builder for chaining.
     */
    public Builder setChatTop(boolean value) {

      chatTop_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool chatTop = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatTop() {
      bitField0_ = (bitField0_ & ~0x00000008);
      chatTop_ = false;
      onChanged();
      return this;
    }

    private boolean chatMute_ ;
    /**
     * <code>bool chatMute = 5;</code>
     * @return The chatMute.
     */
    @java.lang.Override
    public boolean getChatMute() {
      return chatMute_;
    }
    /**
     * <code>bool chatMute = 5;</code>
     * @param value The chatMute to set.
     * @return This builder for chaining.
     */
    public Builder setChatMute(boolean value) {

      chatMute_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool chatMute = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatMute() {
      bitField0_ = (bitField0_ & ~0x00000010);
      chatMute_ = false;
      onChanged();
      return this;
    }

    private boolean chatDel_ ;
    /**
     * <code>bool chatDel = 6;</code>
     * @return The chatDel.
     */
    @java.lang.Override
    public boolean getChatDel() {
      return chatDel_;
    }
    /**
     * <code>bool chatDel = 6;</code>
     * @param value The chatDel to set.
     * @return This builder for chaining.
     */
    public Builder setChatDel(boolean value) {

      chatDel_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool chatDel = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatDel() {
      bitField0_ = (bitField0_ & ~0x00000020);
      chatDel_ = false;
      onChanged();
      return this;
    }

    private long updateTimestamp_ ;
    /**
     * <code>int64 updateTimestamp = 7;</code>
     * @return The updateTimestamp.
     */
    @java.lang.Override
    public long getUpdateTimestamp() {
      return updateTimestamp_;
    }
    /**
     * <code>int64 updateTimestamp = 7;</code>
     * @param value The updateTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTimestamp(long value) {

      updateTimestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 updateTimestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      updateTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private long delTimestamp_ ;
    /**
     * <code>int64 delTimestamp = 8;</code>
     * @return The delTimestamp.
     */
    @java.lang.Override
    public long getDelTimestamp() {
      return delTimestamp_;
    }
    /**
     * <code>int64 delTimestamp = 8;</code>
     * @param value The delTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setDelTimestamp(long value) {

      delTimestamp_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 delTimestamp = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000080);
      delTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private long lastReadMsgId_ ;
    /**
     * <code>int64 lastReadMsgId = 9;</code>
     * @return The lastReadMsgId.
     */
    @java.lang.Override
    public long getLastReadMsgId() {
      return lastReadMsgId_;
    }
    /**
     * <code>int64 lastReadMsgId = 9;</code>
     * @param value The lastReadMsgId to set.
     * @return This builder for chaining.
     */
    public Builder setLastReadMsgId(long value) {

      lastReadMsgId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 lastReadMsgId = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastReadMsgId() {
      bitField0_ = (bitField0_ & ~0x00000100);
      lastReadMsgId_ = 0L;
      onChanged();
      return this;
    }

    private int subStatus_ ;
    /**
     * <code>int32 subStatus = 10;</code>
     * @return The subStatus.
     */
    @java.lang.Override
    public int getSubStatus() {
      return subStatus_;
    }
    /**
     * <code>int32 subStatus = 10;</code>
     * @param value The subStatus to set.
     * @return This builder for chaining.
     */
    public Builder setSubStatus(int value) {

      subStatus_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 subStatus = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubStatus() {
      bitField0_ = (bitField0_ & ~0x00000200);
      subStatus_ = 0;
      onChanged();
      return this;
    }

    private long joinGroupTimestamp_ ;
    /**
     * <code>int64 joinGroupTimestamp = 11;</code>
     * @return The joinGroupTimestamp.
     */
    @java.lang.Override
    public long getJoinGroupTimestamp() {
      return joinGroupTimestamp_;
    }
    /**
     * <code>int64 joinGroupTimestamp = 11;</code>
     * @param value The joinGroupTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setJoinGroupTimestamp(long value) {

      joinGroupTimestamp_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int64 joinGroupTimestamp = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearJoinGroupTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000400);
      joinGroupTimestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ImChat)
  }

  // @@protoc_insertion_point(class_scope:ImChat)
  private static final com.github.xuning888.helloim.api.protobuf.common.v1.ImChat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.xuning888.helloim.api.protobuf.common.v1.ImChat();
  }

  public static com.github.xuning888.helloim.api.protobuf.common.v1.ImChat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImChat>
      PARSER = new com.google.protobuf.AbstractParser<ImChat>() {
    @java.lang.Override
    public ImChat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ImChat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImChat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.xuning888.helloim.api.protobuf.common.v1.ImChat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

