// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/chat.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

public interface ImChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 chatId = 2;</code>
   * @return The chatId.
   */
  long getChatId();

  /**
   * <code>int32 chatType = 3;</code>
   * @return The chatType.
   */
  int getChatType();

  /**
   * <code>bool chatTop = 4;</code>
   * @return The chatTop.
   */
  boolean getChatTop();

  /**
   * <code>bool chatMute = 5;</code>
   * @return The chatMute.
   */
  boolean getChatMute();

  /**
   * <code>bool chatDel = 6;</code>
   * @return The chatDel.
   */
  boolean getChatDel();

  /**
   * <code>int64 updateTimestamp = 7;</code>
   * @return The updateTimestamp.
   */
  long getUpdateTimestamp();

  /**
   * <code>int64 delTimestamp = 8;</code>
   * @return The delTimestamp.
   */
  long getDelTimestamp();

  /**
   * <code>int64 lastReadMsgId = 9;</code>
   * @return The lastReadMsgId.
   */
  long getLastReadMsgId();

  /**
   * <code>int32 subStatus = 10;</code>
   * @return The subStatus.
   */
  int getSubStatus();

  /**
   * <code>int64 joinGroupTimestamp = 11;</code>
   * @return The joinGroupTimestamp.
   */
  long getJoinGroupTimestamp();
}
