// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/common/v1/common.proto

// Protobuf Java Version: 3.25.6
package com.github.xuning888.helloim.api.protobuf.common.v1;

public interface ImUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int32 userType = 2;</code>
   * @return The userType.
   */
  int getUserType();

  /**
   * <code>string userName = 3;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 3;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string icon = 4;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <code>string icon = 4;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>string mobile = 5;</code>
   * @return The mobile.
   */
  java.lang.String getMobile();
  /**
   * <code>string mobile = 5;</code>
   * @return The bytes for mobile.
   */
  com.google.protobuf.ByteString
      getMobileBytes();

  /**
   * <code>string deviceId = 6;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string deviceId = 6;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string extra = 7;</code>
   * @return The extra.
   */
  java.lang.String getExtra();
  /**
   * <code>string extra = 7;</code>
   * @return The bytes for extra.
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  /**
   * <code>int32 userStatus = 8;</code>
   * @return The userStatus.
   */
  int getUserStatus();

  /**
   * <code>.google.protobuf.Timestamp createdAt = 9;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 9;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp createdAt = 9;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp updatedAt = 10;</code>
   * @return Whether the updatedAt field is set.
   */
  boolean hasUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 10;</code>
   * @return The updatedAt.
   */
  com.google.protobuf.Timestamp getUpdatedAt();
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();
}
