server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: helloim-chatlist
  redis:
    host: ${REDIS_ADDR}
dubbo:
  application:
    name: helloim-chatlist
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS}
  registry:
    address: ${ZK_ADDRESS}
    group: helloim
    timeout: 10000
  consumer:
    check: false

