server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: helloim-chatlist
  redis:
    host: ${REDIS_ADDR:127.0.0.1}
dubbo:
  application:
    name: helloim-chatlist
    logger: slf4j
    qos-enable: false
  metadata-report:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
  registry:
    address: ${ZK_ADDRESS:zookeeper://127.0.0.1:2181}
    group: helloim
    timeout: 10000
  consumer:
    check: false

